### ISSUE TITLE
It throws exception: com.alibaba.fastjson.JSONArray cannot be cast to com.alibaba.fastjson.JSONObject

### ISSUE THREAD

**Issue by gewanbo** [FTChinese/FTC-API#1]
2016-01-07 14:34:50.555 [System-akka.actor.default-dispatcher-11] ERROR com.wanbo.easyapi.server.lib.SeederManager - The seed string is :{"body":{"ielement":[]},"head":{"transactiontype":"11001"}}
java.lang.ClassCastException: com.alibaba.fastjson.JSONArray cannot be cast to com.alibaba.fastjson.JSONObject
        at com.alibaba.fastjson.JSONObject.getJSONObject(JSONObject.java:109) ~[fastjson-1.2.5.jar:na]
        at com.wanbo.easyapi.server.lib.SeederManager.loadSeed(SeederManager.scala:45) [easyapi.server-1.0.21-SNAPSHOT.jar:na]
        at com.wanbo.easyapi.server.lib.SeederManager.farming(SeederManager.scala:76) [easyapi.server-1.0.21-SNAPSHOT.jar:na]
        at com.wanbo.easyapi.server.actors.Worker.process(Worker.scala:57) ~[easyapi.server-1.0.21-SNAPSHOT.jar:na]
        at com.wanbo.easyapi.server.actors.Worker$$anonfun$receive$1.applyOrElse(Worker.scala:33) ~[easyapi.server-1.0.21-SNAPSHOT.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.10-2.3.9.jar:na]
        at com.wanbo.easyapi.server.actors.Worker.aroundReceive(Worker.scala:15) ~[easyapi.server-1.0.21-SNAPSHOT.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.10-2.3.9.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.10-2.3.9.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[akka-actor_2.10-2.3.9.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[akka-actor_2.10-2.3.9.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[akka-actor_2.10-2.3.9.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) ~[scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) ~[scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.10.4.jar:na]

**Comment by gewanbo** [comment]
Fixed.
