### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by gewanbo** [FTChinese/FTC-API#3]
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:693)
        at com.ftchinese.workers.Seeder_61009.onHandle(Seeder_61009.scala:78)
        at com.wanbo.easyapi.server.lib.SeederManager.farming(SeederManager.scala:109)
        at com.wanbo.easyapi.server.actors.Worker.process(Worker.scala:57)
        at com.wanbo.easyapi.server.actors.Worker$$anonfun$receive$1.applyOrElse(Worker.scala:33)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at com.wanbo.easyapi.server.actors.Worker.aroundReceive(Worker.scala:15)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by gewanbo** [comment]
Fixed.
